### ISSUE TITLE
How do i use this ?

### ISSUE THREAD

**Issue by TrongHieu90** [spissvinkel/simplex-noise-ts#1]
How do i create a noise 2d function with this ? Also i see the permutation table is created in runtime. Is there anyway to implement the original permutation table for fast look up ?

**Comment by spissvinkel** [comment]
Hi,

You can initialize the table once at the start of your program.
First of all you will need a PRNG - you can use `Math.random()` for this, or if you need repeatable results you can use a seedable generator like this one: [spissvinkel/alea-ts](https://github.com/spissvinkel/alea-ts).

Example:
```typescript
import { mkSimplexNoise } from '@spissvinkel/simplex-noise';

const prng = Math.random;
const { noise2D } = mkSimplexNoise(prng);    // Do this once to initialize the permutation tables
...
let value = noise2D(x, y);                   // Later use this function as often as you need
```
